classdef TestFormatSpec
    properties(Constant)
        TestFormats = [
            TestFormat(1, 1051, [
                TestSectionGap('First gap', 'FZ', -67, 100), ...
                SpringRateTestSection('Static spring rate'), ...
                TestSectionGap('Second gap', 'V', 40.2, 1), ...
                SpringRateTestSection('First dynamic spring rate'), ...
                TestSectionGap('Third gap', 'FZ', -200, 200), ...
                SpringRateTestSection('Second dynamic spring rate'), ...
                TestSectionGap('Initial SA gap', 'SA', -4, 1), ...
                TestSectionRepeatedWSpec('Inc angles', 'IA', BoundsFinderN(5, 0.5), [
                    LoadsTestSection('Inc angles loads', 'FZ', BoundsFinderN(5, 250), [
                        TestSectionGap('Inc angles first SA gap', 'SA', -4, 1), ...
                        SASweepTestSection('Inc angles SA sweeps'), ...
                        TestSectionGap('Inc angles second SA gap', 'SA', -4, 1)
                        ]), ...
                    SpecifiedEndTestSection('Inc angles end')
                    ]), ...
                SpringRateTestSection('Post-test dynamic spring rate'), ...
                TestSectionGap('Spring gap', 'FZ', -50, 150), ...
                SpringRateTestSection('Second static spring rate'), ...
                TestSectionGap('Spring gap 2', 'FZ', -200, 150), ...
                SpringRateTestSection('Third dynamic spring rate'), ...
                TestSectionGap('Spring gap 3', 'FZ', -200, 50), ...
                TestSectionRepeatedWSpec('First pressures', 'P', BoundsFinderN(4, 5), [
                    SpringRateTestSection('First pressures dynamic spring rate'), ...
                    TestSectionGap('First pressures initial gap', 'FZ', -640, 100), ...
                    SpringRateTestSection('First pressures dynamic spring rate'), ...
                    LoadsTestSection('First pressures loads', 'FZ', BoundsFinderN(2, 200), [
                        TestSectionGap('First pressures first SA gap', 'SA', -4, 1), ...
                        SASweepTestSection('First pressures SA sweeps'), ...
                        TestSectionGap('First pressures second SA gap', 'SA', -4, 1)
                        ])
                    ]), ...
                TestSectionRepeatedWSpec('Final 12psi', 'P', BoundsFinderN(1, 5), [
                    SpringRateTestSection('Final 12psi dynamic spring rate'), ...
                    LoadsTestSection('Final 12psi loads', 'FZ', BoundsFinderN(2, 200), [
                        TestSectionGap('Final 12psi first SA gap', 'SA', -4, 1), ...
                        SASweepTestSection('Final 12psi SA sweeps'), ...
                        SpecifiedEndTestSection('Final 12psi loads end')
                        ]), ...
                    SpecifiedEndTestSection('Final 12psi end')
                    ])
                ]), ...
            TestFormat(2, 1052, [
                TestSectionGap('First gap', 'FZ', -67, 100), ...
                SpringRateTestSection('Static spring rate'), ...
                TestSectionGap('Second gap', 'V', 40.2, 1), ...
                SpringRateTestSection('First dynamic spring rate'), ...
                TestSectionGap('Third gap', 'FZ', -200, 200), ...
                SpringRateTestSection('Second dynamic spring rate'), ...
                TestSectionGap('Initial SA gap', 'SA', -4, 1), ...
                TestSectionRepeatedWSpec('Inc angles', 'IA', BoundsFinderN(5, 0.5), [
                    LoadsTestSection('Inc angles loads', 'FZ', BoundsFinderN(5, 250), [
                        TestSectionGap('Inc angles first SA gap', 'SA', -4, 1), ...
                        SASweepTestSection('Inc angles SA sweeps'), ...
                        TestSectionGap('Inc angles second SA gap', 'SA', -4, 1)
                        ]), ...
                    SpecifiedEndTestSection('Inc angles end')
                    ]), ...
                SpringRateTestSection('Post-test dynamic spring rate'), ...
                TestSectionGap('Spring gap', 'FZ', -50, 150), ...
                SpringRateTestSection('Second static spring rate'), ...
                TestSectionGap('Spring gap 2', 'FZ', -200, 150), ...
                SpringRateTestSection('Third dynamic spring rate'), ...
                TestSectionGap('Spring gap 3', 'FZ', -200, 50), ...
                TestSectionRepeatedWSpec('First pressures', 'P', BoundsFinderN(4, 5), [
                    SpringRateTestSection('First pressures dynamic spring rate'), ...
                    TestSectionGap('First pressures initial gap', 'FZ', -640, 100), ...
                    SpringRateTestSection('First pressures dynamic spring rate'), ...
                    LoadsTestSection('First pressures loads', 'FZ', BoundsFinderN(2, 200), [
                        TestSectionGap('First pressures first SA gap', 'SA', -4, 1), ...
                        SASweepTestSection('First pressures SA sweeps'), ...
                        TestSectionGap('First pressures second SA gap', 'SA', -4, 1)
                        ])
                    ]), ...
                TestSectionRepeatedWSpec('Final 12psi', 'P', BoundsFinderN(1, 5), [
                    SpringRateTestSection('Final 12psi dynamic spring rate'), ...
                    LoadsTestSection('Final 12psi loads', 'FZ', BoundsFinderN(2, 200), [
                        TestSectionGap('Final 12psi first SA gap', 'SA', -4, 1), ...
                        SASweepTestSection('Final 12psi SA sweeps'), ...
                        SpecifiedEndTestSection('Final 12psi loads end')
                        ]), ...
                    SpecifiedEndTestSection('Final 12psi end')
                    ])
                ]), ...
            TestFormat(3, 1175, [
                SpringRateTestSection('Static spring rate'), ...
                TestSectionGap('First gap', 'V', 40.2, 1), ...
                SpringRateTestSection('First dynamic spring rate'), ...
                WarmupAndConditioningTestSection('Warmup and conditioning'), ...
                TestSectionGap('Initial SA gap', 'SA', -4, 1), ...
                TestSectionRepeatedWSpec('Inc angles', 'IA', BoundsFinderN(5, 0.5), ...
                    LoadsTestSection('Inc angles loads', 'FZ', BoundsFinderN(5, 200), [
                        TestSectionGap('Inc angles first SA gap', 'SA', -4, 1), ...
                        SASweepTestSection('Inc angles SA sweeps'), ...
                        SpecifiedEndTestSection('Spring rate inc angles end')
                        ])), ...
                SpringRateTestSection('Extra dynamic spring rate'), ...
                TestSectionGap('Spring gap', 'FZ', -200, 50), ...
                SpringRateTestSection('Second dynamic spring rate'), ...
                TestSectionGap('Spring gap 3', 'FZ', -640, 50), ...
                SpringRateTestSection('Extra dynamic spring rate 2'), ...
                TestSectionGap('Spring gap 4', 'FZ', -200, 50), ...
                TestSectionRepeatedWSpec('First pressures', 'P', BoundsFinderN(3, 5), [
                    TestSectionGap('First pressures initial gap', 'FZ', -200, 100), ...
                    SpringRateTestSection('First pressures dynamic spring rate'), ...
                    LoadsTestSection('First pressures loads', 'FZ', BoundsFinderN(5, 200), [
                        TestSectionGap('First pressures first SA gap', 'SA', -4, 1), ...
                        SASweepTestSection('First pressures SA sweeps'), ...
                        TestSectionGap('First pressures second SA gap', 'SA', -4, 1)
                        ])
                    ]), ...
                TestSectionRepeatedWSpec('Final 12psi', 'P', BoundsFinderN(1, 5), [
                    TestSectionGap('Final 12psi initial gap', 'FZ', -200, 100), ...
                    SpringRateTestSection('Final 12psi dynamic spring rate'), ...
                    LoadsTestSection('Final 12psi loads', 'FZ', BoundsFinderN(5, 200), [
                        TestSectionGap('Final 12psi first SA gap', 'SA', -4, 1), ...
                        SASweepTestSection('Final 12psi SA sweeps'), ...
                        SpecifiedEndTestSection('Final 12psi loads end')
                        ]), ...
                    SpecifiedEndTestSection('Final 12psi end')
                    ])
                ]), ...
            TestFormat(4, 1320, [
                TestSectionGap('First gap', 'FZ', -200, 100), ...
                TestSectionRepeatedWSpec('Static spring rate inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.1), [
                    SpringRateTestSection('Static spring rate'), ...
                    SpecifiedEndTestSection('Static spring rate end')
                    ]), ...
                TestSectionGap('Second gap', 'FZ', -200, 100), ...
                TestSectionRepeatedWSpec('First dynamic spring rate inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.1), [
                    SpringRateTestSection('First dynamic spring rate'), ...
                    SpecifiedEndTestSection('First dynamic spring rate end')
                    ]), ...
                ColdToHotTestSection('Cold to hot'), ...
                TestSectionRepeatedWSpec('Second dynamic spring rate inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.1), [
                    SpringRateTestSection('Second dynamic spring rate'), ...
                    SpecifiedEndTestSection('Second dynamic spring rate end')
                    ]), ...
                WarmupAndConditioningTestSection('Warmup and conditioning'), ...
                TestSectionRepeatedWSpec('Pressures', 'P', BoundsFinderN(5, 5), [
                    TestSectionGap('Pressures first gap', 'FZ', -1550, 200), ...
                    TestSectionRepeatedWSpec('Inc angles', 'IA', BoundsFinderSpec([0, 2, 4, 1, 3], 0.1), [
                        LoadsTestSection('Loads', 'FZ', BoundsFinderN(5, 200), [
                            TestSectionGap('Loads first SA gap', 'SA', -4, 1), ...
                            SASweepTestSection('SA sweeps'), ...
                            SpecifiedEndTestSection('Loads end')
                            ]), ...
                        SpecifiedEndTestSection('Inc angles end')
                        ]), ...
                    TestSectionGap('Pressures second gap', 'IA', 0, 0.1), ...
                    SpringRateTestSection('Pressures dynamic spring rate'), ...
                    SpecifiedEndTestSection('Pressures end')
                    ])
                ]), ...
            TestFormat(5, 1464, [
                TestSectionGap('First gap', 'FZ', -200, 100), ...
                TestSectionRepeatedWSpec('Static spring rate inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.1), [
                    SpringRateTestSection('Static spring rate'), ...
                    SpecifiedEndTestSection('Static spring rate end')
                    ]), ...
                TestSectionGap('Second gap', 'FZ', -200, 100), ...
                TestSectionRepeatedWSpec('First dynamic spring rate inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.1), [
                    SpringRateTestSection('First dynamic spring rate'), ...
                    SpecifiedEndTestSection('First dynamic spring rate end')
                    ]), ...
                ColdToHotTestSection('Cold to hot'), ...
                TestSectionRepeatedWSpec('Second dynamic spring rate inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.1), [
                    SpringRateTestSection('Second dynamic spring rate'), ...
                    SpecifiedEndTestSection('Second dynamic spring rate end')
                    ]), ...
                WarmupAndConditioningTestSection('Warmup'), ...
                TestSectionRepeatedWSpec('Pressures', 'P', BoundsFinderSpec([82.5, 67, 95, 55, 82.5], 10), [
                    TestSectionGap('Pressures first gap', 'FZ', -1550, 150), ...
                    TestSectionRepeatedWSpec('Inc angles', 'IA', BoundsFinderN(5, 0.5), [
                        LoadsTestSection('Loads', 'FZ', BoundsFinderN(5, 200), [
                            TestSectionGap('Loads first gap', 'SA', -4, 1), ...
                            SASweepTestSection('SA sweeps'), ...
                            SpecifiedEndTestSection('Loads end'), ...
                            ]), ...
                        SpecifiedEndTestSection('Inc angles end')
                        ]), ...
                    SpringRateTestSection('Pressures dynamic spring rate'), ...
                    SpecifiedEndTestSection('Pressures end')
                    ]), ...
                ]), ...
            TestFormat(6, 1654, [
                ColdToHotTestSection('Cold to hot'), ...
                TestSectionRepeatedWSpec('Initial spring rate inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.5), [
                    SpringRateTestSectionSpec('Initial spring rate', [-200, -420, -650, -1100, -1530], 120), ...
                    SpecifiedEndTestSection('Spring rate inc angles end')
                    ]), ...
                BreakInTestSection('Break-in', 13), ...
                TestSectionRepeatedWSpec('First pressures', 'P', BoundsFinderSpec([83, 70, 97, 55], 5), [
                    SAConditioningTestSectionSpec('SA conditioning', -1100, 200), ...
                    TestSectionRepeatedWSpec('First inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.5), [
                        LoadsTestSection('First loads', 'FZ', BoundsFinderSpec([-1530, -650, -200, -1100, -420], 200), [
                            TestSectionGap('Loads gap', 'SA', -4, 1), ...
                            SASweepTestSectionSpec('First SA sweeps', -4, 0.5), ...
                            SpecifiedEndTestSection('Loads end')
                            ]), ...
                        SpecifiedEndTestSection('Inc angles end'), ...
                        ]), ...
                    TestSectionRepeatedWSpec('First pressures dynamic spring rate inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.5), [
                        SpringRateTestSectionSpec('First pressure dynamic spring rate', [-200, -420, -650, -1100, -1530], 200), ...
                        SpecifiedEndTestSection('Pressures spring rate end')
                        ]), ...
                    SpecifiedEndTestSection('Pressures end')
                    ]), ...
                ColdToHotTestSection('Cold to hot'), ...
                TestSectionRepeatedWSpec('Remaining 25mph', 'V', BoundsFinderSpec(41, 5), ...
                    TestSectionRepeatedWSpec('Final 12psi pressure', 'P', BoundsFinderSpec(83, 5), [
                        SAConditioningTestSectionSpec('SA conditioning', -1100, 200), ...
                        TestSectionRepeatedWSpec('Final 12psi inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.5), [
                            LoadsTestSection('Final 12psi loads', 'FZ', BoundsFinderSpec([-1530, -650, -200, -1100, -420], 100), [
                                TestSectionGap('Final 12psi loads gap', 'SA', -4, 1), ...
                                SASweepTestSectionSpec('Final 12psi SA sweeps', -4, 0.5), ...
                                SpecifiedEndTestSection('Final 12psi loads end')
                                ]), ...
                            SpecifiedEndTestSection('Final 12psi inc angles end')
                            ]), ...
                        TestSectionRepeatedWSpec('Final 12psi spring rate inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.5), [
                            SpringRateTestSectionSpec('Final 12psi spring rate', [-200, -420, -650, -1100, -1530], 200), ...
                            SpecifiedEndTestSection('Final 12psi spring rate inc angles end')
                            ]), ...
                        SpecifiedEndTestSection('Final 12psi pressure end')
                        ])), ...
                TestSectionRepeatedWSpec('Other speeds', 'V', BoundsFinderSpec([24, 72.4], 2), [
                    LoadsTestSection('Other speeds loads', 'FZ', BoundsFinderSpec([-1530, -650, -200, -1100, -420], 100), [
                        TestSectionGap('Other speeds loads gap', 'SA', -4, 1), ...
                        SASweepTestSectionSpec('Other speeds SA sweeps', -4, 0.5), ...
                        SpecifiedEndTestSection('Other speeds loads end')
                        ]), ...
                    SpecifiedEndTestSection('Speeds end')
                    ]), ...
                CleaningTestSection('Cleaning')
                ]), ...
            TestFormat(7, 1706, [
                ColdToHotTestSection('Cold to hot'), ...
                TestSectionRepeatedWSpec('Initial spring rate inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.5), [
                    SpringRateTestSectionSpec('Initial spring rate', [-200, -420, -650, -1100, -1530], 120), ...
                    SpecifiedEndTestSection('Spring rate inc angles end')
                    ]), ...
                BreakInTestSection('Break-in', 13), ...
                TestSectionRepeatedWSpec('First pressures', 'P', BoundsFinderSpec([83, 70, 97, 55], 5), [
                    SAConditioningTestSectionSpec('SA conditioning', -1100, 200), ...
                    TestSectionRepeatedWSpec('First inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.5), [
                        LoadsTestSection('First loads', 'FZ', BoundsFinderSpec([-1530, -650, -200, -1100, -420], 200), [
                            TestSectionGap('Loads gap', 'SA', -4, 1), ...
                            SASweepTestSectionSpec('First SA sweeps', 4, 0.5), ...
                            SpecifiedEndTestSection('Loads end')
                            ]), ...
                        SpecifiedEndTestSection('Inc angles end'), ...
                        ]), ...
                    TestSectionRepeatedWSpec('First pressures dynamic spring rate inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.5), [
                        SpringRateTestSectionSpec('First pressure dynamic spring rate', [-200, -420, -650, -1100, -1530], 200), ...
                        SpecifiedEndTestSection('Pressures spring rate end')
                        ]), ...
                    SpecifiedEndTestSection('Pressures end')
                    ]), ...
                ColdToHotTestSection('Cold to hot'), ...
                TestSectionRepeatedWSpec('Remaining 25mph', 'V', BoundsFinderSpec(41, 5), ...
                    TestSectionRepeatedWSpec('Final 12psi pressure', 'P', BoundsFinderSpec(83, 5), [
                        SAConditioningTestSectionSpec('SA conditioning', -1100, 200), ...
                        TestSectionRepeatedWSpec('Final 12psi inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.5), [
                            LoadsTestSection('Final 12psi loads', 'FZ', BoundsFinderSpec([-1530, -650, -200, -1100, -420], 100), [
                                TestSectionGap('Final 12psi loads gap', 'SA', -4, 1), ...
                                SASweepTestSectionSpec('Final 12psi SA sweeps', -4, 0.5), ...
                                SpecifiedEndTestSection('Final 12psi loads end')
                                ]), ...
                            SpecifiedEndTestSection('Final 12psi inc angles end')
                            ]), ...
                        TestSectionRepeatedWSpec('Final 12psi spring rate inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.5), [
                            SpringRateTestSectionSpec('Final 12psi spring rate', [-200, -420, -650, -1100, -1530], 200), ...
                            SpecifiedEndTestSection('Final 12psi spring rate inc angles end')
                            ]), ...
                        SpecifiedEndTestSection('Final 12psi pressure end')
                        ])), ...
                TestSectionRepeatedWSpec('Other speeds', 'V', BoundsFinderSpec([24, 72.4], 2), [
                    LoadsTestSection('Other speeds loads', 'FZ', BoundsFinderSpec([-1530, -650, -200, -1100, -420], 100), [
                        TestSectionGap('Other speeds loads gap', 'SA', -4, 1), ...
                        SASweepTestSectionSpec('Other speeds SA sweeps', -4, 0.5), ...
                        SpecifiedEndTestSection('Other speeds loads end')
                        ]), ...
                    SpecifiedEndTestSection('Speeds end')
                    ]), ...
                CleaningTestSection('Cleaning')
                ]), ...
            TestFormat(8, 1965, [
                ColdToHotTestSection('Cold to hot'), ...
                TestSectionRepeatedWSpec('Initial spring rate inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.5), [
                    SpringRateTestSectionSpec('Initial spring rate', [-200, -420, -650, -870, -1100], 120), ...
                    SpecifiedEndTestSection('Spring rate inc angles end')
                    ]), ...
                BreakInTestSection('Break-in', 13), ...
                TestSectionRepeatedWSpec('First pressures', 'P', BoundsFinderSpec([83, 70, 97, 55], 10), [
                    SAConditioningTestSectionSpec('SA conditioning', -1100, 200), ...
                    TestSectionRepeatedWSpec('First inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.5), [
                        LoadsTestSection('First loads', 'FZ', BoundsFinderSpec([-870, -650, -200, -1100, -420], 200), [
                            TestSectionGap('Loads gap', 'SA', -4, 1), ...
                            SASweepTestSectionSpec('First SA sweeps', -4, 0.5), ...
                            SpecifiedEndTestSection('Loads end')
                            ]), ...
                        SpecifiedEndTestSection('Inc angles end'), ...
                        ]), ...
                    TestSectionRepeatedWSpec('First pressures dynamic spring rate inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.5), [
                        SpringRateTestSectionSpec('First pressure dynamic spring rate', [-200, -420, -650, -870, -1100], 200), ...
                        SpecifiedEndTestSection('Pressures spring rate end')
                        ]), ...
                    SpecifiedEndTestSection('Pressures end')
                    ]), ...
                ColdToHotTestSection('Cold to hot'), ...
                TestSectionRepeatedWSpec('Remaining 25mph', 'V', BoundsFinderSpec(41, 2), ...
                    TestSectionRepeatedWSpec('Final 12psi pressure', 'P', BoundsFinderSpec(83, 10), [
                        SAConditioningTestSectionSpec('SA conditioning', -1100, 200), ...
                        TestSectionRepeatedWSpec('Final 12psi inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.5), [
                            LoadsTestSection('Final 12psi loads', 'FZ', BoundsFinderSpec([-870, -650, -200, -1100, -420], 100), [
                                TestSectionGap('Final 12psi loads gap', 'SA', -4, 1), ...
                                SASweepTestSectionSpec('Final 12psi SA sweeps', -4, 0.5), ...
                                SpecifiedEndTestSection('Final 12psi loads end')
                                ]), ...
                            SpecifiedEndTestSection('Final 12psi inc angles end')
                            ]), ...
                        TestSectionRepeatedWSpec('Final 12psi spring rate inc angles', 'IA', BoundsFinderSpec([0, 2, 4], 0.5), [
                            SpringRateTestSectionSpec('Final 12psi spring rate', [-200, -420, -650, -870, -1100], 200), ...
                            SpecifiedEndTestSection('Final 12psi spring rate inc angles end')
                            ]), ...
                        SpecifiedEndTestSection('Final 12psi pressure end')
                        ])), ...
                TestSectionRepeatedWSpec('Other speeds', 'V', BoundsFinderSpec([24, 72.4], 2), [
                    LoadsTestSection('Other speeds loads', 'FZ', BoundsFinderSpec([-870, -650, -200, -1100, -420], 100), [
                        TestSectionGap('Other speeds loads gap', 'SA', -4, 1), ...
                        SASweepTestSectionSpec('Other speeds SA sweeps', -4, 0.5), ...
                        SpecifiedEndTestSection('Other speeds loads end')
                        ]), ...
                    SpecifiedEndTestSection('Speeds end')
                    ]), ...
                TestSectionRepeatedWSpec('Inc angle sweeps pressures', 'P', BoundsFinderSpec([55, 70, 83, 97], 5), [
                    LoadsTestSection('Inc angle sweeps loads', 'FZ', BoundsFinderSpec([-430, -1100, -1530], 200), [
                        IncAngleSweepTestSection('Inc angle sweeps'), ...
                        SpecifiedEndTestSection('Inc angle sweeps end')
                        ]), ...
                    SpecifiedEndTestSection('Inc angle sweeps loads end')
                    ]), ...
                CleaningTestSection('Cleaning')
                ]), ...
            ]
    end
    
    methods(Static)
        function format = getTestFormats
            format = TestFormatSpec.TestFormats;
        end
    end
end